name: Build Jar

on:
  push:
    paths:
      - 'Main.java'
  pull_request:
    paths:
      - 'Main.java'
  workflow_dispatch:

jobs:
  build-and-clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile and Package JAR
        run: |
          mkdir -p out
          javac Main.java -d out
          cd out
          jar cfe server.jar Main Main.class

      - name: Upload server.jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: server.jar
          path: out/server.jar

      - name: Install GitHub CLI
        run: |
          sudo apt install gh -y
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Delete previous artifacts (keep current)
        env:
          GH_REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        run: |
          echo "Current run ID: ${RUN_ID}"
          artifacts=$(gh api repos/${GH_REPO}/actions/artifacts --paginate -q '.artifacts[] | "\(.id) \(.workflow_run.id)"')

          while IFS= read -r line; do
            artifact_id=$(echo $line | cut -d ' ' -f1)
            artifact_run_id=$(echo $line | cut -d ' ' -f2)

            if [ "$artifact_run_id" != "$RUN_ID" ]; then
              echo "Deleting artifact ID $artifact_id (from run $artifact_run_id)"
              gh api -X DELETE repos/${GH_REPO}/actions/artifacts/$artifact_id
            else
              echo "✅ Keeping current artifact ID $artifact_id"
            fi
          done <<< "$artifacts"
